### PR TITLE
Basic screen with topmenu

### PR DESCRIPTION
**Pull request by arist0v**
Create a Basic UI with top Menu

### CODE REVIEW

**Comment by tim-hellhake** [comment]
@benfrancis the code looks ok, I think we can merge it.
I made a screenshot to save you some time:

image

**Review by benfrancis — CHANGES_REQUESTED** [review]
That's super helpful, thank you @tim-hellhake, and I'm very sorry for the delay in reviewing these PRs @arist0v, I just haven't had chance yet to set up an Android development environment or put an Android phone in developer mode.

This looks fine with one minor comment that should be resolved before landing. Could you please change the font of the "Things" heading to Open Sans. Zilla slab is only really used for the wordmark.

Thanks!

**Comment by arist0v** [comment]
change done

**Comment by tim-hellhake** [comment]
@benfrancis image

**Review by tim-hellhake — APPROVED** [review]
The unused `setCurrentScreen` method is still in there but I don't want to be too pedantic.
It's up to @benfrancis now :smile:

**Review by benfrancis — APPROVED** [review]
Thanks!

**Comment by arist0v** [comment]
Have you look if it's used on the next pr??(i based my code on how to i
found so maybe it's just because i try to split my pr ;-) )

Le jeu. 12 mai 2022, 20 h 04, Tim Hellhake ***@***.***> a
écrit :

**Pull request merged**
