### PR TITLE
Drawer menu

### PR DESCRIPTION
**Pull request by arist0v**
create drawer menu

### CODE REVIEW

**Comment by tim-hellhake** [comment]
I just installed it on my phone.
Looks great!

**Comment by arist0v** [comment]
Dont merge this one before #59

**Comment by tim-hellhake** [comment]
image

**Review by benfrancis — CHANGES_REQUESTED** [review]
Some points on the UI:
- "Webthings" should be capitalised as "WebThings" (see [branding guidelines](https://webthings.io/legal/trademark/#branding-guidelines))
- Please left-align the WebThings wordmark at the top of the menu
- [Here](https://drive.google.com/file/d/10WXgMj1kZueiIRTTk69CbTNEBQO9zSZW/view?usp=sharing) is an icon to use for the "Things" menu entry
- Is it possible to remove the background colour on the heading of the main menu and use it as a highlight colour for the selected menu item instead? This is to match the web app

See a quick mockup below:
webthings_app-main_menu

**Comment by arist0v** [comment]
image

**Comment by arist0v** [comment]
here we go for the first request, i work on the other!

**Comment by arist0v** [comment]
image
the onclick dark blue is also set but hard to capture

**Review by benfrancis — APPROVED** [review]
The UI looks better now, thank you.

Once there's actually a Things screen the Things menu item should be highlighted when it is selected.

**Comment by arist0v** [comment]
Great i keep a not about it


Le ven. 13 mai 2022, à 13 h 00, Ben Francis ***@***.***> a
écrit :

**Pull request merged**
