### PR TITLE
Themes

### PR DESCRIPTION
**Pull request by arist0v**
Settings up basic App Themes

### CODE REVIEW

**Comment by tim-hellhake** [comment]
Wonderful!
That's the kind of PR I like.
@benfrancis maybe you should look at this one first.

**Review by tim-hellhake — APPROVED** [review]
Wonderful!
That's the kind of PR I like.
@benfrancis maybe you should look at this one first.

**Comment by arist0v** [comment]
So ready we could merge?

**Comment by tim-hellhake** [comment]
I'm ok with it, but @benfrancis needs to approve it as well.
He knows best which colors and fonts are correct.

**Comment by arist0v** [comment]
i used the offical one he provide but np, i'll wait his approval to be sure!

**Comment by arist0v** [comment]
If no one disagree, i suggest to merge this commit, and if we need to fix color or font or other thing just open an issue and fix it so we could keep going on the project

**Review by benfrancis — APPROVED** [review]

**Pull request merged**
